image: docker:stable

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay
  ARG_ARCH: "amd64"
  ARG_BASEIMG: "openjdk"
  ARG_BASEVERS: "8-jre-slim"

services:
- docker:stable-dind


build:beta:amd64:
  only:
    - master
  before_script:
    - apk add --no-cache curl gzip
    - uname -a
    - docker version
    - export DL_URL=https://dl.ubnt.com/unifi/5.9.4-b647df56b7/unifi_sysvinit_all.deb
    - curl -sSL $DL_URL
    - export BRANCH_VERSION="$(echo $DL_URL | grep -o -E '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+[^//]*')"
    # - export VERSION_STABLE="$(echo $BRANCH_VERSION | grep -o '^[^-]*')"
    - export SHA_COMMIT="$(echo ${CI_COMMIT_SHA} | cut -b-8)"
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - docker build --pull -t "${CI_REGISTRY_IMAGE}/unifi:unstable" .
    - docker tag  "${CI_REGISTRY_IMAGE}/unifi:unstable" "${CI_REGISTRY_IMAGE}/unifi:${BRANCH_VERSION}"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:unstable"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:${BRANCH_VERSION}"
    - docker rmi "${CI_REGISTRY_IMAGE}/unifi:unstable"
  tags:
    - docker

build:stable:amd64:
  only:
    - master
  before_script:
    - apk add --no-cache curl gzip
    - uname -a
    - docker version
    - export VERSION_STABLE="$(./ci-get-unifi-version.sh stable)"
    - export BRANCH_VERSION="$(echo ${VERSION_STABLE} | cut -d. -f-2)"
    - export SHA_COMMIT="$(echo ${CI_COMMIT_SHA} | cut -b-8)"
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - docker build --pull -t "${CI_REGISTRY_IMAGE}/unifi:stable" .
    - docker tag  "${CI_REGISTRY_IMAGE}/unifi:stable" "${CI_REGISTRY_IMAGE}/unifi:latest"
    - docker tag  "${CI_REGISTRY_IMAGE}/unifi:stable" "${CI_REGISTRY_IMAGE}/unifi:${VERSION_STABLE}"
    - docker tag  "${CI_REGISTRY_IMAGE}/unifi:stable" "${CI_REGISTRY_IMAGE}/unifi:${VERSION_STABLE}-b${CI_PIPELINE_ID}"
    - docker tag  "${CI_REGISTRY_IMAGE}/unifi:stable" "${CI_REGISTRY_IMAGE}/unifi:${VERSION_STABLE}-s${SHA_COMMIT}"
    - docker tag  "${CI_REGISTRY_IMAGE}/unifi:stable" "${CI_REGISTRY_IMAGE}/unifi:${BRANCH_VERSION}"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:stable"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:latest"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:${VERSION_STABLE}"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:${VERSION_STABLE}-b${CI_PIPELINE_ID}"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:${VERSION_STABLE}-s${SHA_COMMIT}"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:${BRANCH_VERSION}"
    - docker rmi "${CI_REGISTRY_IMAGE}/unifi:stable" "${CI_REGISTRY_IMAGE}/unifi:${VERSION_STABLE}" "${CI_REGISTRY_IMAGE}/unifi:latest"
  tags:
    - docker

build:oldstable:amd64:
  only:
    - oldstable
  before_script:
    - apk add --no-cache curl gzip
    - export VERSION_OLDSTABLE="$(./ci-get-unifi-version.sh oldstable)"
    - export BRANCH_VERSION="$(echo ${VERSION_STABLE} | cut -d. -f-2)"
    - export SHA_COMMIT="$(echo ${CI_COMMIT_SHA} | cut -b-8)"
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - docker build --pull -t "${CI_REGISTRY_IMAGE}/unifi:oldstable" .
    - docker tag  "${CI_REGISTRY_IMAGE}/unifi:oldstable" "${CI_REGISTRY_IMAGE}/unifi:${VERSION_OLDSTABLE}"
    - docker tag  "${CI_REGISTRY_IMAGE}/unifi:oldstable" "${CI_REGISTRY_IMAGE}/unifi:${VERSION_OLDSTABLE}-b${CI_PIPELINE_ID}"
    - docker tag  "${CI_REGISTRY_IMAGE}/unifi:oldstable" "${CI_REGISTRY_IMAGE}/unifi:${VERSION_OLDSTABLE}-s${SHA_COMMIT}"
    - docker tag  "${CI_REGISTRY_IMAGE}/unifi:oldstable" "${CI_REGISTRY_IMAGE}/unifi:${BRANCH_VERSION}"
    - docker tag  "${CI_REGISTRY_IMAGE}/unifi:oldstable" "${CI_REGISTRY_IMAGE}/unifi:lts"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:oldstable"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:${VERSION_OLDSTABLE}"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:${VERSION_OLDSTABLE}-b${CI_PIPELINE_ID}"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:${VERSION_OLDSTABLE}-s${SHA_COMMIT}"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:${BRANCH_VERSION}"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:lts"
    - docker rmi "${CI_REGISTRY_IMAGE}/unifi:oldstable" "${CI_REGISTRY_IMAGE}/unifi:${VERSION_OLDSTABLE}"
  tags:
    - docker

build:dev:amd64:
  only:
    - branches
  except:
    - master
    - oldstable
    - testing
  before_script:
    - apk add --no-cache curl gzip
    - export VERSION_STABLE="$(./ci-get-unifi-version.sh unifi-5.6)"
    - export BRANCH_VERSION="$(echo ${VERSION_STABLE} | cut -d. -f-2)"
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - docker build --pull -t "${CI_REGISTRY_IMAGE}/unifi:dev-${VERSION_STABLE}-$CI_COMMIT_REF_SLUG" .
    - docker tag  "${CI_REGISTRY_IMAGE}/unifi:dev-${VERSION_STABLE}-$CI_COMMIT_REF_SLUG" "${CI_REGISTRY_IMAGE}/unifi:dev-latest"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:dev-${VERSION_STABLE}-$CI_COMMIT_REF_SLUG"
    - docker push "${CI_REGISTRY_IMAGE}/unifi:dev-latest"
    - docker rmi "${CI_REGISTRY_IMAGE}/unifi:dev-${VERSION_STABLE}-$CI_COMMIT_REF_SLUG" "${CI_REGISTRY_IMAGE}/unifi:dev-latest"
  tags:
    - docker
